server:
  # 当前应用所在的Web服务器监听的本地端口
  port: 8081
  servlet:
    # 应用的上下文路径
    context-path: /SpringBoot-WebSimple
    # 启用默认的Servlet
    register-default-servlet: true

spring:
  mvc:
    static-path-pattern: /resources/**

#    formcontent:
#      filter:
#        enabled: true

#    hiddenmethod:
#      filter:
#        enabled: true

#  web:
#    resources:
#      add-mappings: false

#  web:
#    resources:
#      # 这里可以传入单个，也可以传入列表
#      static-locations: classpath:/myResources/